#
# BASE CONFIGURATION
#

# `base_url` should only be changed if your site isn't hosted at the root of a domain.
# `domain` is used to generate absolute URLs and is only required if `feed` is set to true.
#
#   Example:
#       http://my-site.com/
#           base_url: /
#           domain: my-site.com
#       http://my-site.com/my-blog/
#           base_url: /my-blog/
#           domain: my-site.com
base_url: /blog/
domain: shamansir.github.com
# Posts URL
posts_url: /articles/<title>/

#
# METADATA
#

# Used in header meta tags and the site feed.
author: Ulric Wilfred
# A description of your site to be used in header meta tags.
description: Blog about programming and only about it. No word about onion. At all. Totally none.
# Used in the site feed.
email: shaman.sir@gmail.com
# Your site's subtitle.
subtitle: shaman.sir's telling you about stuff
# Your site's title.
title: No word about onion


#
# DISPLAY SETTINGS
#

# The amount of posts that will be displayed on the front page.
#   Leave blank or set to `false` to disable.
post_limit: 10
#time_locale: ru_RU.UTF-8


#
# THIRD PARTY SETTINGS
#

# If you'd like to enable Google Analytics for your site, set this to your tracking code.
analytics:
# Set this to True to enable an Atom feed of your site.
#   NOTE: `author`, `domain`, and `title` must be set to generate a valid feed.
feed: true
# Links to profiles on various social networking sites.
#   Set any of the following to your username/ID on that site to enable it.
social:
    dribbble:
    facebook: shaman.sir
    github: shamansir
    google_plus:
    lastfm: #shamansir
    stack_overflow: 167262
    steam: #shamansir
    twitter: shaman_sir
    # TODO: add coderwall & speakerdeck


#
# Chances are you probably don't need to touch anything below here.
#
archive_layout: archive.html
archives_url: /archives/
jinja:
    extensions:
        - jinja2.ext.loopcontrols
misaka:
    render_flags:
        toc: true
tag_layout: tag.html
tags_url: /tags/
